#!/usr/bin/env python3
"""Create the team's radio channels on the local Mumble server over Ice.

Run it with OpenTAKServer's Python, which has Ice and the Mumble interface file:
  ~/.opentakserver_venv/bin/python setup/radio_channels.py "Main" "Team 1" "Command"

Channels that already exist are left alone. The first one becomes the channel
people land in when they connect.
"""

import os
import sys
import time

import Ice

import opentakserver

Ice.loadSlice("", ["-I" + Ice.getSliceDir(),
                   os.path.join(os.path.dirname(opentakserver.__file__), "mumble", "Murmur.ice")])
import Murmur  # noqa: E402  (generated by loadSlice above)


def main():
    names = [n.strip() for n in sys.argv[1:] if n.strip()]
    if not names:
        sys.exit(__doc__)

    props = Ice.createProperties()
    props.setProperty("Ice.Default.EncodingVersion", "1.0")
    props.setProperty("Ice.ImplicitContext", "Shared")
    data = Ice.InitializationData()
    data.properties = props
    with Ice.initialize(data) as ice:
        meta = Murmur.MetaPrx.uncheckedCast(ice.stringToProxy("Meta:tcp -h 127.0.0.1 -p 6502"))
        for attempt in range(20):
            try:
                servers = meta.getBootedServers()
                break
            except Ice.ConnectionRefusedException:
                time.sleep(1)
        else:
            sys.exit("Couldn't reach the Mumble server's Ice port (127.0.0.1:6502). Is it running?")

        for server in servers:
            existing = {c.name: cid for cid, c in server.getChannels().items() if c.parent == 0}
            ids = []
            for name in names:
                if name in existing:
                    ids.append(existing[name])
                else:
                    ids.append(server.addChannel(name, 0))
                    print(f"Added channel: {name}")
            server.setConf("defaultchannel", str(ids[0]))
            print(f"Channels ready: {', '.join(names)} (people start in {names[0]})")


if __name__ == "__main__":
    main()
